### ISSUE TITLE
command not working

### ISSUE THREAD

**Issue by le-cardinal** [davidfstr/pydeps#2]
Traceback (most recent call last):
  File "/home/eccf/examples/python_examples/davidstr/pydeps/pydeps.py", line 186, in <module>
    main(sys.argv[1:])
  File "/home/eccf/examples/python_examples/davidstr/pydeps/pydeps.py", line 58, in main
    info = read_source_file(filepath)
  File "/home/eccf/examples/python_examples/davidstr/pydeps/pydeps.py", line 154, in read_source_file
    line = line.strip('\r\n')
TypeError: a bytes-like object is required, not 'str'

**Comment by davidfstr** [comment]
@le-cardinal Please provide specific steps to get the traceback that you posted.

**Comment by cristianounix** [comment]
line = line.strip('\r\n')

where, line is equal:

> b'from contextlib import contextmanager\n'

**Comment by davidfstr** [comment]
@cristianounix , I need a full set of steps:
* Clone source code from URL X.
* Run command Y.
* See error Z.
